"""add assessment tables

Revision ID: 7e55aac9daee
Revises: 94162b09c78b
Create Date: 2025-12-17 15:46:02.106779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e55aac9daee'
down_revision: Union[str, None] = '94162b09c78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert INTEGER to BOOLEAN using USING clause
    op.execute("ALTER TABLE quizzes ALTER COLUMN is_active TYPE BOOLEAN USING is_active::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_comment='Квиз активен и используется для оценки',
               existing_nullable=False)
    # ### end Alembic commands ###
