"""add all models

Revision ID: 94162b09c78b
Revises: c90d0161a6f2
Create Date: 2025-12-17 00:52:26.865614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94162b09c78b'
down_revision: Union[str, None] = 'c90d0161a6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID трека'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Название трека (например, 'Python Backend', 'Frontend')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание трека'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Трек активен и доступен для подачи заявок'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда трек был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда трек последний раз обновлялся'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID кандидата'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Ссылка на пользователя'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Полное имя кандидата'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Номер телефона'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Местоположение (город, страна)'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='Часовой пояс кандидата'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда профиль был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда профиль последний раз обновлялся'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=True)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID уведомления'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Ссылка на пользователя'),
    sa.Column('type', sa.Enum('TELEGRAM', 'EMAIL', name='notification_type'), nullable=False, comment='Тип уведомления: telegram или email'),
    sa.Column('template_name', sa.String(length=255), nullable=False, comment='Название шаблона уведомления'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Данные для шаблона в формате JSONB'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status'), nullable=False, comment='Статус отправки уведомления'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Когда уведомление было отправлено'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда уведомление было создано'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID квиза'),
    sa.Column('track_id', sa.Integer(), nullable=False, comment='Ссылка на трек'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='Квиз активен и используется для оценки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда квиз был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда квиз последний раз обновлялся'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_track_id'), 'quizzes', ['track_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID команды'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название команды'),
    sa.Column('hiring_manager_id', sa.UUID(), nullable=False, comment='Ссылка на нанимающего менеджера (рекрутера)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда команда была создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда команда последний раз обновлялась'),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_hiring_manager_id'), 'teams', ['hiring_manager_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID попытки квиза'),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Ссылка на кандидата'),
    sa.Column('quiz_id', sa.Integer(), nullable=False, comment='Ссылка на квиз'),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ответы кандидата в формате JSONB: {question_id: answer}'),
    sa.Column('score', sa.Float(), nullable=False, comment='Итоговый балл (0-100)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда квиз был завершен'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_candidate_id'), 'quiz_attempts', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=True)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID вопроса'),
    sa.Column('quiz_id', sa.Integer(), nullable=False, comment='Ссылка на квиз'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='Текст вопроса'),
    sa.Column('question_type', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='question_type'), nullable=False, comment='Тип вопроса: single_choice или multiple_choice'),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Варианты ответов в формате JSONB: {option_id: option_text}'),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Правильный ответ в формате JSONB (option_id или массив option_ids)'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Сложность вопроса (1-5)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда вопрос был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда вопрос последний раз обновлялся'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID резюме'),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Ссылка на кандидата'),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Образование в формате JSONB: {degree, field, institution, year}'),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Опыт работы в формате JSONB: [{company, position, years, description}]'),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Навыки в формате JSONB массива строк'),
    sa.Column('portfolio_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ссылки на портфолио в формате JSONB массива строк'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда резюме было создано'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда резюме последний раз обновлялось'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID вакансии'),
    sa.Column('track_id', sa.Integer(), nullable=False, comment='Ссылка на трек'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='Ссылка на команду'),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Требования к кандидатам в формате JSONB: {required_skills, nice_to_have_skills, min_experience_years}'),
    sa.Column('is_open', sa.Boolean(), nullable=False, comment='Вакансия открыта и доступна для заявок'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда вакансия была создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда вакансия последний раз обновлялась'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_team_id'), 'vacancies', ['team_id'], unique=False)
    op.create_index(op.f('ix_vacancies_track_id'), 'vacancies', ['track_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID заявки'),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Ссылка на кандидата'),
    sa.Column('resume_id', sa.UUID(), nullable=False, comment='Ссылка на резюме'),
    sa.Column('quiz_attempt_id', sa.UUID(), nullable=False, comment='Ссылка на попытку квиза'),
    sa.Column('status', sa.Enum('SUBMITTED', 'SCREENING', 'INTERVIEWING', 'REJECTED', 'HIRED', name='application_status'), nullable=False, comment='Общий статус заявки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда заявка была создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда заявка последний раз обновлялась'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=True)
    op.create_index(op.f('ix_applications_quiz_attempt_id'), 'applications', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_table('vacancy_assessments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID оценки'),
    sa.Column('resume_id', sa.UUID(), nullable=False, comment='Ссылка на резюме'),
    sa.Column('vacancy_id', sa.Integer(), nullable=False, comment='Ссылка на вакансию'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Общий балл оценки (0-100)'),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Детализация оценки в формате JSONB: {skills_match, experience_match, education_match}'),
    sa.Column('reasoning', sa.Text(), nullable=False, comment='Обоснование оценки от AI'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда оценка была создана'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_assessments_id'), 'vacancy_assessments', ['id'], unique=True)
    op.create_index(op.f('ix_vacancy_assessments_resume_id'), 'vacancy_assessments', ['resume_id'], unique=False)
    op.create_index(op.f('ix_vacancy_assessments_vacancy_id'), 'vacancy_assessments', ['vacancy_id'], unique=False)
    op.create_table('vacancy_applications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID заявки на вакансию'),
    sa.Column('application_id', sa.UUID(), nullable=False, comment='Ссылка на общую заявку'),
    sa.Column('vacancy_id', sa.Integer(), nullable=False, comment='Ссылка на вакансию'),
    sa.Column('assessment_id', sa.UUID(), nullable=True, comment='Ссылка на AI-оценку (может быть null)'),
    sa.Column('recruiter_notes', sa.Text(), nullable=True, comment='Заметки рекрутера'),
    sa.Column('status', sa.Enum('PENDING', 'SENT_TO_HM', 'HM_APPROVED', 'HM_REJECTED', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'OFFER', 'REJECTED', name='vacancy_application_status'), nullable=False, comment='Статус заявки на вакансию'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда заявка на вакансию была создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда заявка на вакансию последний раз обновлялась'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['vacancy_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_applications_application_id'), 'vacancy_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_vacancy_applications_assessment_id'), 'vacancy_applications', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_vacancy_applications_id'), 'vacancy_applications', ['id'], unique=True)
    op.create_index(op.f('ix_vacancy_applications_vacancy_id'), 'vacancy_applications', ['vacancy_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID интервью'),
    sa.Column('vacancy_application_id', sa.UUID(), nullable=False, comment='Ссылка на заявку на вакансию'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='Запланированное время интервью'),
    sa.Column('candidate_confirmed', sa.Boolean(), nullable=False, comment='Кандидат подтвердил интервью'),
    sa.Column('hm_confirmed', sa.Boolean(), nullable=False, comment='Нанимающий менеджер подтвердил интервью'),
    sa.Column('hm_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Обратная связь от HM в формате JSONB: {rating, notes}'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='interview_status'), nullable=False, comment='Статус интервью'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда интервью было создано'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда интервью последний раз обновлялось'),
    sa.ForeignKeyConstraint(['vacancy_application_id'], ['vacancy_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=True)
    op.create_index(op.f('ix_interviews_vacancy_application_id'), 'interviews', ['vacancy_application_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный UUID пользователя',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=320),
               comment='Email пользователя, используется как логин',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               comment='Bcrypt-хэш пароля',
               existing_nullable=False)
    # Create user_role enum type
    user_role_enum = postgresql.ENUM('CANDIDATE', 'RECRUITER', name='user_role', create_type=False)
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # Convert existing VARCHAR values to enum using USING clause
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role USING role::user_role")

    # Add comment
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CANDIDATE', 'RECRUITER', name='user_role'),
               comment='Роль пользователя: candidate или recruiter',
               existing_nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID пользователя в Telegram для уведомлений',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Аккаунт активен/заблокирован',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда аккаунт был создан',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда аккаунт последний раз обновлялся',
               existing_nullable=False)
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда аккаунт последний раз обновлялся',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда аккаунт был создан',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Аккаунт активен/заблокирован',
               existing_nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ID пользователя в Telegram для уведомлений',
               existing_nullable=True)
    # Convert enum back to VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(50) USING role::text")

    # Drop user_role enum type
    op.execute("DROP TYPE IF EXISTS user_role")

    # Remove comment
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Роль пользователя: candidate или recruiter',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt-хэш пароля',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email пользователя, используется как логин',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный UUID пользователя',
               existing_nullable=False)
    op.drop_index(op.f('ix_interviews_vacancy_application_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_vacancy_applications_vacancy_id'), table_name='vacancy_applications')
    op.drop_index(op.f('ix_vacancy_applications_id'), table_name='vacancy_applications')
    op.drop_index(op.f('ix_vacancy_applications_assessment_id'), table_name='vacancy_applications')
    op.drop_index(op.f('ix_vacancy_applications_application_id'), table_name='vacancy_applications')
    op.drop_table('vacancy_applications')
    op.drop_index(op.f('ix_vacancy_assessments_vacancy_id'), table_name='vacancy_assessments')
    op.drop_index(op.f('ix_vacancy_assessments_resume_id'), table_name='vacancy_assessments')
    op.drop_index(op.f('ix_vacancy_assessments_id'), table_name='vacancy_assessments')
    op.drop_table('vacancy_assessments')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_quiz_attempt_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_vacancies_track_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_team_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_candidate_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_teams_hiring_manager_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_quizzes_track_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('tracks')
    # ### end Alembic commands ###
