"""update team model remove hiring manager add description

Revision ID: cfd7ce05a97b
Revises: 7e55aac9daee
Create Date: 2025-12-17 16:00:10.484992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd7ce05a97b'
down_revision: Union[str, None] = '7e55aac9daee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True, comment='Описание команды и её направления'))
    op.drop_index(op.f('ix_teams_hiring_manager_id'), table_name='teams')
    op.drop_constraint(op.f('teams_hiring_manager_id_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'hiring_manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('hiring_manager_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на нанимающего менеджера (рекрутера)'))
    op.create_foreign_key(op.f('teams_hiring_manager_id_fkey'), 'teams', 'users', ['hiring_manager_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_teams_hiring_manager_id'), 'teams', ['hiring_manager_id'], unique=False)
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
