"""major_refactor_telegram_auth_hiring_managers_candidate_pools

Revision ID: eaa7a0c6db30
Revises: cfd7ce05a97b
Create Date: 2025-12-17 21:08:36.024421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaa7a0c6db30'
down_revision: Union[str, None] = 'cfd7ce05a97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiring_managers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID менеджера'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('calendly_id', sa.String(length=255), nullable=True, comment='ID в системе Calendly'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.String(length=255), nullable=False, comment='Фамилия'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Когда профиль был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Когда профиль последний раз обновлялся'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_managers_id'), 'hiring_managers', ['id'], unique=True)
    op.create_index(op.f('ix_hiring_managers_telegram_id'), 'hiring_managers', ['telegram_id'], unique=True)
    op.create_table('candidate_pools',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID записи в пуле'),
    sa.Column('vacancy_id', sa.Integer(), nullable=False, comment='Ссылка на вакансию'),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Ссылка на кандидата'),
    sa.Column('status', sa.Enum('VIEWED', 'SELECTED', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'FINALIST', 'OFFER_SENT', 'REJECTED', name='candidate_pool_status'), nullable=False, comment='Текущий статус кандидата в воронке'),
    sa.Column('interview_scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время назначенного интервью'),
    sa.Column('interview_link', sa.String(length=500), nullable=True, comment='Ссылка на интервью (Calendly/Meet)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Заметки HM о кандидате'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Когда кандидат попал в этот статус'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Когда запись последний раз обновлялась'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'candidate_id', name='uq_vacancy_candidate')
    )
    op.create_index('idx_vacancy_status', 'candidate_pools', ['vacancy_id', 'status'], unique=False)
    op.create_index(op.f('ix_candidate_pools_candidate_id'), 'candidate_pools', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_pools_id'), 'candidate_pools', ['id'], unique=True)
    op.create_index(op.f('ix_candidate_pools_status'), 'candidate_pools', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_pools_vacancy_id'), 'candidate_pools', ['vacancy_id'], unique=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # Drop tables in the correct order to respect foreign key constraints
    # First drop tables that depend on other tables
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_vacancy_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_vacancy_applications_application_id'), table_name='vacancy_applications')
    op.drop_index(op.f('ix_vacancy_applications_assessment_id'), table_name='vacancy_applications')
    op.drop_index(op.f('ix_vacancy_applications_id'), table_name='vacancy_applications')
    op.drop_index(op.f('ix_vacancy_applications_vacancy_id'), table_name='vacancy_applications')
    op.drop_table('vacancy_applications')
    op.drop_index(op.f('ix_vacancy_assessments_id'), table_name='vacancy_assessments')
    op.drop_index(op.f('ix_vacancy_assessments_resume_id'), table_name='vacancy_assessments')
    op.drop_index(op.f('ix_vacancy_assessments_vacancy_id'), table_name='vacancy_assessments')
    op.drop_table('vacancy_assessments')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_quiz_attempt_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_quiz_attempts_candidate_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    # Now drop quizzes after its dependents are gone
    op.drop_index(op.f('ix_quizzes_track_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # Clear existing candidates data since schema is changing drastically
    op.execute('TRUNCATE TABLE candidates CASCADE')
    # Modify candidates table
    op.add_column('candidates', sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'))
    op.add_column('candidates', sa.Column('preferred_tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Список ID треков в порядке приоритета'))
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.create_index(op.f('ix_candidates_telegram_id'), 'candidates', ['telegram_id'], unique=True)
    op.drop_constraint(op.f('candidates_user_id_fkey'), 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'timezone')
    op.drop_column('candidates', 'user_id')
    # Clear existing vacancies data since schema is changing drastically
    op.execute('TRUNCATE TABLE vacancies CASCADE')
    # Create vacancy_status enum type
    op.execute("CREATE TYPE vacancy_status AS ENUM ('DRAFT', 'ACTIVE', 'ABORTED')")
    # Modify vacancies table and drop FK to teams
    op.add_column('vacancies', sa.Column('hiring_manager_id', sa.UUID(), nullable=False, comment='Ссылка на hiring manager который создал вакансию'))
    op.add_column('vacancies', sa.Column('description', sa.Text(), nullable=False, comment='Описание позиции'))
    op.add_column('vacancies', sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'ABORTED', name='vacancy_status', create_type=False), nullable=False, comment='Статус вакансии: draft, active, aborted'))
    op.add_column('vacancies', sa.Column('next_interview_at', sa.DateTime(timezone=True), nullable=True, comment='Дата ближайшего собеседования'))
    op.add_column('vacancies', sa.Column('next_interview_link', sa.String(length=500), nullable=True, comment='Ссылка на собеседование (Calendly/Meet)'))
    op.drop_index(op.f('ix_vacancies_team_id'), table_name='vacancies')
    op.create_index(op.f('ix_vacancies_hiring_manager_id'), 'vacancies', ['hiring_manager_id'], unique=False)
    op.create_index(op.f('ix_vacancies_status'), 'vacancies', ['status'], unique=False)
    op.drop_constraint(op.f('vacancies_team_id_fkey'), 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'hiring_managers', ['hiring_manager_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vacancies', 'requirements')
    op.drop_column('vacancies', 'is_open')
    op.drop_column('vacancies', 'team_id')
    # Now safe to drop teams table
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на команду'))
    op.add_column('vacancies', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Вакансия открыта и доступна для заявок'))
    op.add_column('vacancies', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Требования к кандидатам в формате JSONB: {required_skills, nice_to_have_skills, min_experience_years}'))
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('vacancies_team_id_fkey'), 'vacancies', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vacancies_status'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_hiring_manager_id'), table_name='vacancies')
    op.create_index(op.f('ix_vacancies_team_id'), 'vacancies', ['team_id'], unique=False)
    op.drop_column('vacancies', 'next_interview_link')
    op.drop_column('vacancies', 'next_interview_at')
    op.drop_column('vacancies', 'status')
    op.drop_column('vacancies', 'description')
    op.drop_column('vacancies', 'hiring_manager_id')
    op.add_column('candidates', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на пользователя'))
    op.add_column('candidates', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Часовой пояс кандидата'))
    op.create_foreign_key(op.f('candidates_user_id_fkey'), 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_candidates_telegram_id'), table_name='candidates')
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=True)
    op.drop_column('candidates', 'preferred_tracks')
    op.drop_column('candidates', 'telegram_id')
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID резюме'),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на кандидата'),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Образование в формате JSONB: {degree, field, institution, year}'),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Опыт работы в формате JSONB: [{company, position, years, description}]'),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Навыки в формате JSONB массива строк'),
    sa.Column('portfolio_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Ссылки на портфолио в формате JSONB массива строк'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда резюме было создано'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда резюме последний раз обновлялось'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='resumes_candidate_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=True)
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID заявки'),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на кандидата'),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на резюме'),
    sa.Column('quiz_attempt_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на попытку квиза'),
    sa.Column('status', postgresql.ENUM('SUBMITTED', 'SCREENING', 'INTERVIEWING', 'REJECTED', 'HIRED', name='application_status'), autoincrement=False, nullable=False, comment='Общий статус заявки'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда заявка была создана'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда заявка последний раз обновлялась'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='applications_candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], name='applications_quiz_attempt_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='applications_resume_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='applications_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_applications_quiz_attempt_id'), 'applications', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=True)
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Уникальный ID вопроса'),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на квиз'),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False, comment='Текст вопроса'),
    sa.Column('question_type', postgresql.ENUM('SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='question_type'), autoincrement=False, nullable=False, comment='Тип вопроса: single_choice или multiple_choice'),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Варианты ответов в формате JSONB: {option_id: option_text}'),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Правильный ответ в формате JSONB (option_id или массив option_ids)'),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False, comment='Сложность вопроса (1-5)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда вопрос был создан'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда вопрос последний раз обновлялся'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_questions_quiz_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_questions_pkey'))
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teams_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Уникальный ID команды'),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Название команды'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда команда была создана'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда команда последний раз обновлялась'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Описание команды и её направления'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vacancy_assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID оценки'),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на резюме'),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на вакансию'),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Общий балл оценки (0-100)'),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Детализация оценки в формате JSONB: {skills_match, experience_match, education_match}'),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=False, comment='Обоснование оценки от AI'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда оценка была создана'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='vacancy_assessments_resume_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name='vacancy_assessments_vacancy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vacancy_assessments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_vacancy_assessments_vacancy_id'), 'vacancy_assessments', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_vacancy_assessments_resume_id'), 'vacancy_assessments', ['resume_id'], unique=False)
    op.create_index(op.f('ix_vacancy_assessments_id'), 'vacancy_assessments', ['id'], unique=True)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID попытки квиза'),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на кандидата'),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на квиз'),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Ответы кандидата в формате JSONB: {question_id: answer}'),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Итоговый балл (0-100)'),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда квиз был завершен'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='quiz_attempts_candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='quiz_attempts_quiz_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quiz_attempts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=True)
    op.create_index(op.f('ix_quiz_attempts_candidate_id'), 'quiz_attempts', ['candidate_id'], unique=False)
    op.create_table('vacancy_applications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID заявки на вакансию'),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на общую заявку'),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на вакансию'),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=True, comment='Ссылка на AI-оценку (может быть null)'),
    sa.Column('recruiter_notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Заметки рекрутера'),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT_TO_HM', 'HM_APPROVED', 'HM_REJECTED', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'OFFER', 'REJECTED', name='vacancy_application_status'), autoincrement=False, nullable=False, comment='Статус заявки на вакансию'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда заявка на вакансию была создана'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда заявка на вакансию последний раз обновлялась'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='vacancy_applications_application_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['vacancy_assessments.id'], name='vacancy_applications_assessment_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name='vacancy_applications_vacancy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vacancy_applications_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_vacancy_applications_vacancy_id'), 'vacancy_applications', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_vacancy_applications_id'), 'vacancy_applications', ['id'], unique=True)
    op.create_index(op.f('ix_vacancy_applications_assessment_id'), 'vacancy_applications', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_vacancy_applications_application_id'), 'vacancy_applications', ['application_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quizzes_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Уникальный ID квиза'),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на трек'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Квиз активен и используется для оценки'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда квиз был создан'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда квиз последний раз обновлялся'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='quizzes_track_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quizzes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_quizzes_track_id'), 'quizzes', ['track_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID интервью'),
    sa.Column('vacancy_application_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на заявку на вакансию'),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Запланированное время интервью'),
    sa.Column('candidate_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Кандидат подтвердил интервью'),
    sa.Column('hm_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Нанимающий менеджер подтвердил интервью'),
    sa.Column('hm_feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Обратная связь от HM в формате JSONB: {rating, notes}'),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='interview_status'), autoincrement=False, nullable=False, comment='Статус интервью'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда интервью было создано'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда интервью последний раз обновлялось'),
    sa.ForeignKeyConstraint(['vacancy_application_id'], ['vacancy_applications.id'], name=op.f('interviews_vacancy_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('interviews_pkey'))
    )
    op.create_index(op.f('ix_interviews_vacancy_application_id'), 'interviews', ['vacancy_application_id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный UUID уведомления'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ссылка на пользователя'),
    sa.Column('type', postgresql.ENUM('TELEGRAM', 'EMAIL', name='notification_type'), autoincrement=False, nullable=False, comment='Тип уведомления: telegram или email'),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Название шаблона уведомления'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Данные для шаблона в формате JSONB'),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notification_status'), autoincrement=False, nullable=False, comment='Статус отправки уведомления'),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Когда уведомление было отправлено'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Когда уведомление было создано'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=True)
    op.drop_index(op.f('ix_candidate_pools_vacancy_id'), table_name='candidate_pools')
    op.drop_index(op.f('ix_candidate_pools_status'), table_name='candidate_pools')
    op.drop_index(op.f('ix_candidate_pools_id'), table_name='candidate_pools')
    op.drop_index(op.f('ix_candidate_pools_candidate_id'), table_name='candidate_pools')
    op.drop_index('idx_vacancy_status', table_name='candidate_pools')
    op.drop_table('candidate_pools')
    op.drop_index(op.f('ix_hiring_managers_telegram_id'), table_name='hiring_managers')
    op.drop_index(op.f('ix_hiring_managers_id'), table_name='hiring_managers')
    op.drop_table('hiring_managers')
    # ### end Alembic commands ###
